---
etcd:
  expiry: "4380h"
  key:
    algo: "ecdsa"
    size: 256
  details:
    C: "US"
    ST: "GA"
    L: "ATL"
    OU: "outland.dev"
  include_localhost: true
  cluster:
    # Taken from public IPs
    # for i in {1..3}; do printf "ovh$i.outland.dev: %s\n" $(dig +short ovh$i.outland.dev); done
    etcd.outland.dev:
      ovh1.outland.dev:
        - "51.222.107.60"
      ovh2.outland.dev:
        - "192.99.144.103"
      ovh3.outland.dev:
        - "192.99.169.70"

  
